language: python
python:
  - 3.5
  - 3.6

sudo: false

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=pypy

install:
  - pip install coveralls
  - pip install tox
  - pip install -r requirements_dev.txt

script:
  - pre-commit run --all-files
  - tox -e $TOX_ENV

after_script:
  - coveralls

matrix:
  allow_failures:
    - python: 3.6
      env: TOX_ENV=py35
    - python: 3.5
      env: TOX_ENV=py36
